# --- !Ups

CREATE TABLE USERS (
  ID           SERIAL NOT NULL PRIMARY KEY,
  LOGIN        VARCHAR(100),
  NAME         VARCHAR(100),
  PASSWORD     VARCHAR(100) DEFAULT NULL,
  EMAIL        VARCHAR(100) DEFAULT NULL,
  REGISTRATION TIMESTAMP
);

CREATE TABLE LINKS (
  ID      SERIAL NOT NULL PRIMARY KEY,
  USER_ID BIGINT,
  CONTENT TEXT
);

# --- !Downs

DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS LINKS;
